#include "$ROOTIOROOT/share/jobOptions_ReadRec.txt"
#include "$VERTEXFITROOT/share/jobOptions_VertexDbSvc.txt"
#include "$MAGNETICFIELDROOT/share/MagneticField.txt"
#include "$ABSCORROOT/share/jobOptions_AbsCor.txt"
//#include "$HOME/bes/jpsi2invi/v0.1/run/samples/data_664-1_psip_20G-1.txt"
#include "$HOME/bes/jpsi2invi/v0.1/run/samples/data_664-1_psip_20G-$PBS_ARRAYID.txt"


ApplicationMgr.DLLs += {"Jpsi2incl"};
ApplicationMgr.TopAlg += { "Jpsi2incl" };

// Set output level threshold (2=DEBUG, 3=INFO, 4=WARNING, 5=ERROR, 6=FATAL )
MessageSvc.OutputLevel = 5;

// Number of events to be processed (default is 10)
//ApplicationMgr.EvtMax = 5000;
ApplicationMgr.EvtMax = -1;

Jpsi2incl.IsMonteCarlo="false";
//Jpsi2incl.OutputFileName="$HOME/bes/jpsi2invi/v0.1/run/jpsi2incl/data09/jpsi2incl_data09-1.root";
Jpsi2incl.OutputFileName="$HOME/bes/jpsi2invi/v0.1/run/jpsi2incl/data09/jpsi2incl_data09-$PBS_ARRAYID.root";






				
