#include "$ROOTIOROOT/share/jobOptions_ReadRec.txt"
#include "$VERTEXFITROOT/share/jobOptions_VertexDbSvc.txt"
#include "$MAGNETICFIELDROOT/share/MagneticField.txt"
#include "$ABSCORROOT/share/jobOptions_AbsCor.txt"
//#include "$HOME/bes/jpsi2invi/v0.1/run/samples/data_663p01_3650_20G-1.txt"
#include "$HOME/bes/jpsi2invi/v0.1/run/samples/data_663p01_3650_20G-$PBS_ARRAYID.txt"


ApplicationMgr.DLLs += {"Jpsi2invi"};
ApplicationMgr.TopAlg += { "Jpsi2invi" };

// Set output level threshold (2=DEBUG, 3=INFO, 4=WARNING, 5=ERROR, 6=FATAL )
MessageSvc.OutputLevel = 5;

// Number of events to be processed (default is 10)
// ApplicationMgr.EvtMax = 5000;
ApplicationMgr.EvtMax = -1;

Jpsi2invi.IsMonteCarlo="false";
// Jpsi2invi.OutputFileName="$HOME/bes/jpsi2invi/v0.1/run/con3650/jpsi2invi_con3650-test.root";
Jpsi2invi.OutputFileName="$HOME/bes/jpsi2invi/v0.1/run/con3650/jpsi2invi_con3650-$PBS_ARRAYID.root";






				
